# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c53b6fa1cd7f31287dff96453c2176e601e67d8e89a45d76f34e850c204efaec7fb1ba79122f6b0ee260819a43d7e33ceafb231d5f23b6ba0b2082209b6a3e0d

test:
  secret_key_base: d3bc18714dd83c63350780c6acaafe3773f16465ab44b733f1c5bad5b37bfc2b6e5d37c9643f8d23a8f0c7718f0499deaca86d4ee0aec477d3fdc8537fccdab7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
